default:
    image: mcr.microsoft.com/dotnet/sdk:7.0

stages:
    - DateTimeConverter

DateConverter:
    stage: DateTimeConverter
    script:
        - cd DateConverter/DateConverter
        - dotnet build
        - dotnet run
